name: isa-project

static_sites:
  - name: frontend
    github:
      repo: lizhiquan/isa-project
      branch: main
      deploy_on_push: true
    source_dir: client
    routes:
      - path: /
    build_command: yarn run build
  - name: swagger
    github:
      repo: lizhiquan/isa-project
      branch: main
      deploy_on_push: true
    source_dir: swagger
    routes:
      - path: /documentation

services:
  - name: backend
    github:
      repo: lizhiquan/isa-project
      branch: main
      deploy_on_push: true
    source_dir: server
    routes:
      - path: /api
